[workspace]
members = ["jsc", "jsc-sys", "tyr", "node-api", "xtask"]

[profile.release]
lto = true
codegen-units = 1

[workspace.metadata]
icu = { tag = "release-71-1" }
WebKit = { tag = "webkitgtk-2.37.1" }
