name: Docker nightly build

on:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build_image:
    name: Build nodejs-rust:lts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Brooooooklyn
          password: ${{ secrets.GH_TOKEN }}
          logout: false

      - name: Build and push Linux x64
        uses: docker/build-push-action@v3
        with:
          file: linux-x64.Dockerfile
          platforms: linux/amd64
          context: .
          push: true
          tags: ghcr.io/brooooooklyn/jsc-rs/linux-builder:x64

      - name: Build and push Linux x64 musl
        uses: docker/build-push-action@v3
        with:
          file: linux-x64-musl.Dockerfile
          platforms: linux/amd64
          context: .
          push: true
          tags: ghcr.io/brooooooklyn/jsc-rs/linux-builder:x64-musl

      - name: Install latest libc++-dev for cross build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/napi-rs/napi-rs/nodejs:aarch64-16
          options: '--user 0:0 -e GITHUB_TOKEN -v ${{ github.workspace }}/lib/llvm-14:/usr/lib/llvm-14'
          run: >-
            apt-get update &&
            apt-get install -y wget &&
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&
            echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" >> /etc/apt/sources.list &&
            echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" >> /etc/apt/sources.list &&
            apt-get update &&
            apt-get install libc++-14-dev libc++abi-14-dev -y --fix-missing --no-install-recommends
      - name: Build and push Linux aarch64
        uses: docker/build-push-action@v3
        with:
          file: linux-aarch64.Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/brooooooklyn/jsc-rs/linux-builder:aarch64
